### ISSUE TITLE
After loading the page the first item is not preselected

### ISSUE THREAD

**Issue by kecsetihunor** [AndreiLucaci/MySpotify#8]
Hi,

when I open the page or refresh the page, the first item is not preselected. 
It is not user friendly, boss.

Could you fix it, please?

Thank you very much, kind regards,
Hunor

P.S. I very appreciate this work!

**Comment by AndreiLucaci** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/94f2aaf9-22c9-49ad-b876-73715887f6b8-7b3d5ff9-4535-4c93-b957-ff608bffab34-v1.png?transparent=1&palette=1&width=246)
